<?php
/**
 * Database configuration.
 * Tracked in git — contains no secrets.
 *
 * Requires db_psswd.php (gitignored) which defines DB_PASS.
 * In production, db_psswd.php is generated by GitHub Actions before rsync.
 */
define('DB_HOST', 'mysql.agh.edu.pl');
define('DB_NAME', 'argo');
define('DB_USER', 'argo'); //Login
require_once(__DIR__ . '/db_psswd.php'); //Secret
?>