name: Deploy new website with VPN + SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Setup VPN config
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > /tmp/vpn.ovpn 

      - name: Connect to AGH servers using VPN
        run: |
          sudo openvpn --config /tmp/vpn.ovpn --daemon
          for i in {1..30}; do # wait for connection
            echo "Attempt $i (elapsed: $((i-1))s)"
            if ping -c 1 web.agh.edu.pl; then
                echo "Connected successfully"
                exit 0
            fi
            sleep 1
          done

          echo "Failed to connect to VPN"
          exit 1

      - name: Install deployment dependencies
        run: sudo apt-get install -y rsync

      - name: Load ssh deploy key
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.ARGO_DEPLOY_KEY_PRIVATE }}" > ~/.ssh/argo_deploy
          chmod 600 ~/.ssh/argo_deploy

      - name: Deploy via rsync (ssh auth) # Exclude post generation python automation script (tools/)
        run: |
          rsync -avz --delete \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="tools" \
            --exclude="db_backups" \
            --exclude="*.ovpn" \
            --exclude="*.md" \
            -e "ssh -i ~/.ssh/argo_deploy -o StrictHostKeyChecking=no" \
            ./ \
            argo@web.agh.edu.pl:public_html/
